name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to ACR
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and push image
      run: |
        docker build \
          --build-arg PORT=${{secrets.PORT}} \
          --build-arg VITE_AZURE_OPENAI_API_KEY=${{secrets.VITE_AZURE_OPENAI_API_KEY}} \
          --build-arg VITE_AZURE_OPENAI_ENDPOINT=${{secrets.VITE_AZURE_OPENAI_ENDPOINT}} \
          --build-arg VITE_AZURE_OPENAI_VOICE_DEPLOYMENT_NAME=${{secrets.VITE_AZURE_OPENAI_VOICE_DEPLOYMENT_NAME}} \
          --build-arg VITE_AZURE_OPENAI_GENERAL_DEPLOYMENT_NAME=${{secrets.VITE_AZURE_OPENAI_GENERAL_DEPLOYMENT_NAME}} \
          --build-arg VITE_AZURE_SPEECH_KEY=${{secrets.VITE_AZURE_SPEECH_KEY}} \
          --build-arg VITE_AZURE_SPEECH_REGION=${{secrets.VITE_AZURE_SPEECH_REGION}} \
          -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/rhetorica-frontend:latest .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/rhetorica-frontend:latest
